[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "plotly>=6.1.0",
    "reportlab>=4.4.1",
    "sqlalchemy>=2.0.41",
    "streamlit>=1.45.1",
]
